services/web/project/views/movie_recomendation.py
from flask import Blueprint, request, render_template
from flask import flash, redirect, url_for, session, jsonify
from flask_login import LoginManager, login_required, current_user
from .. import log, db
from .auth import role_required, roles_required, User
from ..models.movie_genre import Movie, Genre
from datetime import datetime
import flask_excel as excel
import random

recommendation = Blueprint('recommendation', __name__)

@recommendation.route('/recommendation' , methods=['GET', 'POST'])
@roles_required(['admin', 'user'])
def index():
    genres = Genre.query.all()
    return render_template('movie_recommendation/index.html', genres=genres)


@recommendation.route('/recommendationresult', methods=['GET', 'POST'])
@roles_required(['admin', 'user'])
def recommendationresult():
    genre_select = request.form.get('genre_select')
    genre_search =(str(genre_select))
    log.info("[{0}] has sent a movie recommendation for {1} genre".format(current_user.username, genre_search))
    movies_from_db = Movie.query.all()
    movies = []
    for movie in movies_from_db:
        if current_user not in movie.users:
            for genre in movie.genres:
                if genre.name==genre_search:
                    movies.append(movie)
    movie = random.choice(movies)
    if not movie:
        pass
    return render_template('movie_recommendation/movieresult.html', movie=movie)
     

services/web/project/templates/movie_recommendation/index.html
{% extends "home_layout.html" %}
{% block head  %}

{% endblock %} 

{% block main %}
<div class="d-flex justify-content-center">
    <div><h1 >What should I watch today?</h1>
        <p>Select a genre , and press Submit! </p>
        <form method="POST" action="{{ url_for('recommendation.recommendationresult') }}">
        <select name="genre_select" id="genre_select" class="form-select">
        {% for genre in genres %}
        <option value="{{genre.name}}">{{genre.name}}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-primary my-3">Submit</button>
    </form>
    </div>
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

services/web/project/templates/movie_recommendation/movieresult.html
{% extends "home_layout.html" %}

{% block head  %}

{% endblock %} 

{% block main %}

<div class="text-center">
<h1 >What should I watch today?</h1>


<h5>Title</h5>
<h1>{{movie.title}}</h1>

<hr>

<h5>Overview</h5>

<h4>{{movie.overview}}</h4>

<hr>

<h5>Popularity</h5>

<h4>{{movie.popularity}}</h4>

<hr>

<h5>Release Date</h5>

<h4>{{movie.release_date}}</h4>

<hr>

<h5>Genre</h5>

<h4>
{% for genre in movie.genres %}
-{{genre.name}}<br>
{% endfor %}</h4>


</div>

<a href="/recommendation" class="btn btn-primary my-3">Back</a>


 {% endblock %}

 {% block scripts %}

{% endblock %}