services/web/project/forms/user.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import Form, StringField, PasswordField, HiddenField, StringField, IntegerField, SelectField, BooleanField
from wtforms.validators import DataRequired, InputRequired, EqualTo, Length, Regexp, Optional, ValidationError
from ..models.auth import User, Role
from ..models import *
from wtforms.widgets.core import HiddenInput

class ProfilePassForm(FlaskForm):
    password_old = PasswordField('Current password', [InputRequired(message='This field is required.')])
    password_new = PasswordField('New password',   [InputRequired(),EqualTo('password_new2', message='Password verification failed.'),
                                                Length(min=8, message='Minimum 8 characters.'),
                                                Regexp('^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).+$',
                                                message='Must contain at least one uppercase letter, one lowercase letter, one number, and one other character: @$!%*?&')],
                                                description='The password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one other character: @$!%*?&')
    password_new2 = PasswordField('New password again', [InputRequired(message='This field is required.')])

    def validate_password_old(form, field):
        if not current_user.check_password(field.data):
            raise ValidationError('Incorrect password')


class UserForm(FlaskForm):
    user_id = IntegerField(widget=HiddenInput())
    username = StringField('Username', [InputRequired(message='This field is required.')])
    password = PasswordField('Password', [InputRequired(message='This field is required.'),
                                        EqualTo('confirm', message='Password verification failed.'),
                                        Length(min=8, message='Minimum 8 characters.'),
                                        Regexp('^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).+$',
                                        message='Must contain at least one uppercase letter, one lowercase letter, one number, and one other character: @$!%*?&')
                                        ],
                                        description='The password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one other character: @$!%*?&')
    confirm = PasswordField('Password again', [InputRequired(message='This field is required.')])
    roles = []
    for role in Role.query.all():
        roles.append((role.name, role.name.capitalize()))
    role = SelectField('Roles', choices=roles)

    def validate_username(form, field):
        user_id = form.user_id.data
        if user_id:
            user = User.query.filter(User.username == field.data).filter(User.id!=user_id).first()
        else:
            user = User.query.filter(User.username == field.data).first()
        if user:
            raise ValidationError('The Username is already taken.')

services/web/project/views/user.py
from flask import request, render_template
from flask import flash, redirect, url_for, Blueprint, g
from flask_login import LoginManager, login_required, current_user
from .. import login_manager, db, log
from ..models.auth import User, Role, RoleAssignment
from ..views.auth import role_required, roles_required
from ..forms.user import  UserForm, ProfilePassForm
from ..forms.make_optional import make_optional
from datetime import datetime

user = Blueprint('user', __name__)


@user.route('/user')
@role_required('admin')
def index():
    users = (db.session
             .query(User)
             .join(RoleAssignment)
             .with_entities(User.id, User.username, RoleAssignment.role_name)
             .all())
    return render_template('user/index.html', users=users)


@user.route('/user/add', methods=['GET', 'POST'])
@role_required('admin')
def add():
    form = UserForm(request.form)

    rolesForm = []
    for r in Role.query.all():
        rolesForm.append((r.name, r.name.capitalize()))
    form.role.choices = rolesForm

    if request.method == 'POST' and form.validate():
        username = request.form['username']
        password = request.form['password']
        user = User(username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        role = request.form.get('role')
        RoleAssignment.create(role, user.get_id())

        log.info("[{0}] The User was created: {1}({2})".format(current_user.username,username,role))
        flash('The new User was successfully created: {0}'.format(username), 'success')
        return redirect(url_for('user.index'))
    return render_template('user/add.html', form=form, user=None)


@user.route('/user/edit/<id>', methods=['GET', 'POST'])
@role_required('admin')
def edit(id):
    user = User.query.filter(User.id == id).first()
    if not user:
        flash('The User does not exist or cannot be edited.', 'info')
        return redirect(url_for('user.index'))
    roles = user.get_roles()
    form = UserForm(obj=user)
    rolesForm = []
    for r in Role.query.all():
        rolesForm.append((r.name, r.name.capitalize()))
    form.role.choices = rolesForm

    password = request.form.get('password')
    if not password or password.strip()=='':
        make_optional(form.password)
        make_optional(form.confirm)
    if request.method == 'POST' and form.validate():
        username = request.form.get('username')
        user.set_username(username)
        if password.strip() != '':
            user.set_password(password)
        role = request.form.get('role')
        user.set_role(role)
        db.session.add(user)
        db.session.commit()

        log.info("[{0}] The User has been modified: {1}".format(current_user.username,username))
        flash('The User was successfully modified: {0}'.format(username),'success')
        return redirect(url_for('user.index'))
    else:
        return render_template('user/edit.html',
                               form=form, user=user, roles=roles)


@user.route('/user/delete/<id>', methods=['GET', 'POST'])
@role_required('admin')
def delete(id):
    user = User.query.filter(User.id == id).first()
    if not user:
        flash('The User does not exist or cannot be edited.', 'info')
        return redirect(url_for('user.index'))
    user.remove()
    db.session.commit()

    log.info("[{0}] The User has been deleted: {1}".format(current_user.username,user.username))
    flash('The User has been successfully deleted: {0}'.format(user.username), 'success')
    return redirect(url_for('user.index'))

services/web/project/templates/user/add.html
{% extends "home_layout.html" %}
{% from "macros/render_field.html" import render_field with context %}
{% block main %}
<div class="d-flex justify-content-center">
    <div><h1>Create a new User</h1>
        <form method="POST" action="{{ url_for('user.add') }}" role="form">
            {{ form.csrf_token }}
   
            {{render_field(form.username, class="form-control-label", placeholder="Username")}}
    
            {{render_field(form.password, class="form-control-label", placeholder="Password")}}
    
            {{render_field(form.confirm, class="form-control-label", placeholder="Password")}}
    
            {% set z = form.role.process_data(roles) %}
            {{render_field(form.role, class="form-control-label", placeholder="Role")}}
    

            <button class="btn btn-primary my-4" type="submit">Save</button>
            <a class="btn btn-light my-4" href="/user">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

services/web/project/templates/user/edit.html
{% extends "home_layout.html" %}
{% from "macros/render_field.html" import render_field with context %}
{% block main %}
<div class="d-flex justify-content-center">
<div><h1>Edit User</h1>


    <form method="POST" action="" role="form">
      {{ form.csrf_token }}

      {{ form.user_id(value=user.id) }}

      {{render_field(form.username, class="form-control-label", placeholder="Username")}}
    
      {{render_field(form.password, class="form-control-label", placeholder="Password")}}
  
      {{render_field(form.confirm, class="form-control-label", placeholder="Password")}}
  
      {% set z = form.role.process_data(roles) %}
      {{render_field(form.role, class="form-control-label", placeholder="Role")}}


      <button class="btn btn-primary my-4" type="submit">Save</button>
      <a class="btn btn-light my-4" href="/user">Cancel</a>

      
    </form>
  </div>
</div>

{% endblock %}

services/web/project/templates/user/index.html
{% extends "home_layout.html" %} 

{% block head %}
<link rel="stylesheet" type="text/css" href="/static/vendor/datatables/css/datatables.min.css" />
{% endblock %}  

{% block main %}
<h4><p class="text-center"><b>Users:</b></p></h4>
<div class="table-container">

    {% if current_user.has_role('admin') %}

        <a href="/user/add" class="btn btn-primary my-3">Create a new User</a>

    {% endif %}

    <table id="example" class="table table-bordered table-striped table-hover" style="width: 100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Role</th>
                {% if current_user.has_role('admin') %}
                <th >Operations</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.role_name.capitalize() }}</td>
                {% if current_user.has_role('admin') %}
                <td>
                    <a class="btn btn-primary" href="/user/edit/{{ user.id }}" title="Edit">
                        EDIT
                    </a>
                    {% if current_user.id != user.id and user.id != 1%}

                    <a class="button btn btn-sm btn-light" href="/user/delete/{{ user.id }}" title="Delete"> DELETE</a>

                    {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


    {% endblock %}

    {% block scripts %}
    <script src="/static/vendor/datatables/js/datatables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#example').dataTable( {
        }); 
    
    } );
    </script>
    {% endblock %}